dist: trusty
language: python
python:
  - "3.6"
  - "3.6-dev" # 3.6 development branch


jdk:
  - oraclejdk8

env:
  global:
    - SPARK_HOME=/tmp/spark-2.4.1-bin-hadoop2.7

before_install:
  - chmod +x install-spark.sh
  - pip install --upgrade pip
  - pip install pytest pytest-cov
  - pip install coveralls

install:
  - ./install-spark.sh
  - "pip install -r requirements-test.txt --progress-bar=off"

script:
  - py.test -v --ignore=optimus/dl/ --ignore=examples/ --ignore=tests/creator --ignore=tests/test_dl.py

deploy:
  provider: pypi
  user: "faviovazquez"
  password:
    secure: "YAVFUdSdO0CM4Y92uHjie8StctPb0bh2YZ8HXxMRG6U1hAqZHuh+7FT1yUlH8gqThysm07n7XfoYnfMXGI5sj3xxuiTYrA1eHJwHPn8geRmGMa9j/sWcg8lGk3o48k/Ur//DrKHFvX692ZbCc659zake/IU8MgnOV3NpVnN3lC8OEhNq5D+0WNt0cWYgEIjzUfJUnKJQ9ZF92lyTe0pnn3DwDL6jjaqSVSBYNTgAsf0Rc76BT2fXs8RDiD+zsvxjEoX7U5nazPMtzFUITW1dXzlvpJLXkkVd8HUF4lxBjE2Wm6SFj67sz9VZ+HEGPMzJEFpR3mHHluN00Qw5Nr9RvRG1ivFGPb309LN19jAmuOthPrq65/GSNtlV2bi8ndXCrlu01H2HBXaiF1cXgc++ThIm6mkViQMdGTo+xTvc6UPHTBTH94cIAZCix361yNbiAx4N2XhXGjq+1qMs2Z/qb9mNWw4NVTIsruFSQQXD5iSEwBQltLHo/JEkuR3MgoExyEcQmG7mf/ukgh8Wcenv4UjFOBuEdZgcj4zXn2jva4PaRUGkoJkQsji27Wd8BQjAyNGoz0wnOp7gaLDIOqG/6v+RCNVOfQNBuI1D9OPSzWYSD95/2gLayc+mSgr7hrlgsVsScmz4MdhS4E/0ay3zdQz7MoyMJlHfadfICaJxQI4="
  skip_cleanup: true
  distributions: sdist bdist_wheel
  on:
    tags: true
    branch: master

notifications:
  email: false
  slack:
    secure: "LsrLufpz5yLaouTM0V5uDy8u3QhBeN42PaT2pbkfUNQysSyF6/9LNMbwlhkUjf4IAEpKkFvRgGg5IlEF8XtXf5xaAJQXTG9Y92EUU62Nv5kj47iXHd7O75gvwgSjqs6a60F1vG0nWkgCJZjmr02eeAnwM25b6bxSM3GgnDyq3e+NJAza5vkkvCgUcwxL5ZtoY/za9xdE16yfgTkAhqRwR2ajzxFBsNOgSN04pgF9K69WM2vopY65N/vBDCQAnQPwlglXxCsf6caKqzXL1ohpQCeqOD5nMbyN1LlF51/UPSrQfMYiKt8ogI61+WYFB0jiueX/trCbd5lBvf8dkd9v6mH8o33sPo6f5ddsrwH9IkRrNsKQtxw/AkekteVmXZ5ym61yISfuRuuqVcy6yYqLrSh+oR9/+NWhZhBfxL03Lb6uotfa/v5s36INW+puyX+Ef22voSjeA9HgUhUMUoKiQkkSxMO1Pr2boOPDDsnyzgiUnKPt/S/PnGv03DYQxdLqdtf6b1jmFNaVSZEwINntmZxtxTArsCaehNKMCA9Amz1MHderkPDHLPGHDmzKq2pv5HCW3a2cH/ic4CudHTtC79JR0Ag85lrEAKXVaijV7FDQIcrFO3Tyug6yMd3CGAhmUIBUZHkcUZ1xNiBkv80HwTIrG3RWqklbdoEJmDYSnFQ="

after_success:
  - coveralls
